server:
  port: 8080

spring:
  application:
    name: miniboard
  config:
    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug